version: 2
jobs:
  build:
    working_directory: ~/app-name
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            - dependency-cache-
      - run:
          name: check versions
          command: |
            npm --version
            node --version
            ng --version
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: angular-build
          command: npm ng build --prod --verbose
