defaults: &defaults
  working_directory: ~/app-name
  docker:
    - image: circleci/node:9.5.0

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run:
          name: check versions for node and npm
          command: |
            node --version
            npm --version
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/app-name/node_modules/
      - run:
        name: install dependencies and build project
        command: |
          npm install
          npm run ng build
  deploy:
    <<: *defaults
    steps:
      - setup_remote_docker
      - run:
          name: deploy to docker
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t druckreich/angular-example-app:$TAG -f ./Dockerfile .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push druckreich/angular-example-app:$TAG


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy
#      - build
#      - deploy:
#          requires:
#            - build
