version: 2
jobs:
  build:
    working_directory: ~/app-name
    docker:
      - image: node:9.5.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            - dependency-cache-
      - run:
          name: update npm & @angular/cli
          command: |
            npm install -g npm@5.6.0
            npm install -g @angular/cli@1.6.8
      - run:
          name: check versions
          command: |
            node --version
            npm --version
            ng --version
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/app-name/node_modules
      - run:
          name: angular-build
          command: npm ng build --prod --verbose
