version: 2

jobs:
    build:
        working_directory: ~/angularcli
        # The primary container is an instance of the first list image listed. Your build commands run in this container.
        docker:
            - image: circleci/node:8.9.3-browsers
              environment:
                  CHROME_BIN: "/usr/bin/google-chrome"
        steps:
            - checkout

            - run:
                name: versions
                command: |
                  node --version
                  npm --version
                  yarn --version

        #      Download and cache dependencies
            - restore_cache:
                key: dependency-cache-{{ checksum "yarn.lock" }}

            - run:
                name: yarn-install
                command: yarn --no-progress --pure-lockfile

            - save_cache:
                key: dependency-cache-{{ checksum "yarn.lock" }}
                paths:
                  - ~/.cache/yarn
                  - ./node_modules

            - run:
                name: rebuild node-sass
                command: npm rebuild node-sass
