defaults: &defaults
  working_directory: ~/app-name
  docker:
    - image: circleci/node:9.5.0

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run:
          name: check versions before update
          command: |
            node --version
            npm --version
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/app-name/node_modules/
      - run: npm install
      - run:
          name: angular-build
          command: npm run ng build
  deploy:
    <<: *defaults
    steps:
      - run:
          name: deploy to docker
          command: |
            - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
            - docker push druckreich/angular-example-app
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
        requires:
          - build
